var curr;
var correct = 0;
var wrong = 0;

var phrases = [
	// B
	{ name: "BC", val: "bic", used: false },
	{ name: "BD", val: "bad", used: false },
	{ name: "BF", val: "beef", used: false },
	{ name: "BG", val: "big", used: false },
	{ name: "BH", val: "", used: false },
	{ name: "BI", val: "", used: false },
	{ name: "BJ", val: "bj", used: false },
	{ name: "BK", val: "burger king", used: false },
	{ name: "BL", val: "bud light", used: false },
	{ name: "BM", val: "bm", used: false },
	{ name: "BN", val: "bean", used: false },
	{ name: "BO", val: "bo", used: false },
	{ name: "BP", val: "boop", used: false },
	{ name: "BQ", val: "bisquik", used: false },
	{ name: "BS", val: "bullshit", used: false },
	{ name: "BT", val: "bluetooth", used: false },
	{ name: "BU", val: "boo", used: false },
	{ name: "BV", val: "", used: false },
	{ name: "BW", val: "bow", used: false },
	{ name: "BX", val: "box", used: false },
	// C
	{ name: "CB", val: "cab", used: false },
	{ name: "CD", val: "cd", used: false },
	{ name: "CF", val: "calf", used: false },
	{ name: "CG", val: "cog", used: false },
	{ name: "CH", val: "chuck harrigan", used: false },
	{ name: "CI", val: "", used: false },
	{ name: "CJ", val: "cj", used: false },
	{ name: "CK", val: "cock", used: false },
	{ name: "CL", val: "cool", used: false },
	{ name: "CM", val: "calm", used: false },
	{ name: "CN", val: "clean", used: false },
	{ name: "CO", val: "co", used: false },
	{ name: "CP", val: "coop", used: false },
	{ name: "CQ", val: "", used: false },
	{ name: "CS", val: "csharp", used: false },
	{ name: "CT", val: "connecticut", used: false },
	{ name: "CU", val: "clue", used: false },
	{ name: "CV", val: "calves", used: false },
	{ name: "CW", val: "cow", used: false },
	{ name: "CX", val: "cocks", used: false },
	// D
	{ name: "DB", val: "database", used: false },
	{ name: "DC", val: "dc", used: false },
	{ name: "DF", val: "doof", used: false },
	{ name: "DG", val: "dog", used: false },
	{ name: "DH", val: "", used: false },
	{ name: "DI", val: "die", used: false },
	{ name: "DJ", val: "dj", used: false },
	{ name: "DK", val: "donkey kong", used: false },
	{ name: "DL", val: "download", used: false },
	{ name: "DM", val: "doom", used: false },
	{ name: "DN", val: "dune", used: false },
	{ name: "DO", val: "do", used: false },
	{ name: "DP", val: "dan plows", used: false },
	{ name: "DQ", val: "dairy queen", used: false },
	{ name: "DS", val: "diss", used: false },
	{ name: "DT", val: "downtown", used: false },
	{ name: "DU", val: "", used: false },
	{ name: "DV", val: "dove", used: false },
	{ name: "DW", val: "", used: false },
	{ name: "DX", val: "dicks", used: false },
	// F
	{ name: "FB", val: "facebook", used: false },
	{ name: "FC", val: "fc", used: false },
	{ name: "FD", val: "food", used: false },
	{ name: "FG", val: "field goal", used: false },
	{ name: "FH", val: "field hockey", used: false },
	{ name: "FI", val: "", used: false },
	{ name: "FJ", val: "footjoy", used: false },
	{ name: "FK", val: "fuck", used: false },
	{ name: "FL", val: "florida", used: false },
	{ name: "FM", val: "fm", used: false },
	{ name: "FN", val: "function", used: false },
	{ name: "FO", val: "", used: false },
	{ name: "FP", val: "", used: false },
	{ name: "FQ", val: "", used: false },
	{ name: "FS", val: "effs", used: false },
	{ name: "FT", val: "feet", used: false },
	{ name: "FU", val: "fu", used: false },
	{ name: "FV", val: "", used: false },
	{ name: "FW", val: "forward", used: false },
	{ name: "FX", val: "fox", used: false },
	// G
	{ name: "GB", val: "green bay", used: false },
	{ name: "GC", val: "", used: false },
	{ name: "GD", val: "god", used: false },
	{ name: "GF", val: "", used: false },
	{ name: "GH", val: "", used: false },
	{ name: "GI", val: "gi", used: false },
	{ name: "GJ", val: "good job", used: false },
	{ name: "GK", val: "goal keeper", used: false },
	{ name: "GL", val: "good luck", used: false },
	{ name: "GM", val: "gm", used: false },
	{ name: "GN", val: "goon", used: false },
	{ name: "GO", val: "go", used: false },
	{ name: "GP", val: "gangplank", used: false },
	{ name: "GQ", val: "gq", used: false },
	{ name: "GS", val: "gas", used: false },
	{ name: "GT", val: "got", used: false },
	{ name: "GU", val: "goo", used: false },
	{ name: "GV", val: "", used: false },
	{ name: "GW", val: "", used: false },
	{ name: "GX", val: "gooks", used: false },
	// H
	{ name: "HB", val: "hub", used: false },
	{ name: "HC", val: "", used: false },
	{ name: "HD", val: "hood", used: false },
	{ name: "HF", val: "half", used: false },
	{ name: "HG", val: "hug", used: false },
	{ name: "HI", val: "hi", used: false },
	{ name: "HJ", val: "hj", used: false },
	{ name: "HK", val: "hook", used: false },
	{ name: "HL", val: "hole", used: false },
	{ name: "HM", val: "ham", used: false },
	{ name: "HN", val: "hen", used: false },
	{ name: "HO", val: "ho", used: false },
	{ name: "HP", val: "hop", used: false },
	{ name: "HQ", val: "headquarters", used: false },
	{ name: "HS", val: "high school", used: false },
	{ name: "HT", val: "hot", used: false },
	{ name: "HU", val: "", used: false },
	{ name: "HV", val: "hiv", used: false },
	{ name: "HW", val: "", used: false },
	{ name: "HX", val: "hex", used: false },
	// I
	{ name: "IB", val: "", used: false },
	{ name: "IC", val: "", used: false },
	{ name: "ID", val: "", used: false },
	{ name: "IF", val: "if", used: false },
	{ name: "IG", val: "", used: false },
	{ name: "IH", val: "", used: false },
	{ name: "IJ", val: "", used: false },
	{ name: "IK", val: "", used: false },
	{ name: "IL", val: "", used: false },
	{ name: "IM", val: "", used: false },
	{ name: "IN", val: "in", used: false },
	{ name: "IO", val: "", used: false },
	{ name: "IP", val: "", used: false },
	{ name: "IQ", val: "", used: false },
	{ name: "IS", val: "", used: false },
	{ name: "IT", val: "it", used: false },
	{ name: "IU", val: "", used: false },
	{ name: "IV", val: "iv", used: false },
	{ name: "IW", val: "", used: false },
	{ name: "IX", val: "", used: false },
	// J
	{ name: "JB", val: "just because", used: false },
	{ name: "JC", val: "just curious", used: false },
	{ name: "JD", val: "jack daniels", used: false },
	{ name: "JF", val: "", used: false },
	{ name: "JG", val: "", used: false },
	{ name: "JH", val: "", used: false },
	{ name: "JI", val: "", used: false },
	{ name: "JK", val: "just kidding", used: false },
	{ name: "JL", val: "", used: false },
	{ name: "JM", val: "jim", used: false },
	{ name: "JN", val: "", used: false },
	{ name: "JO", val: "joe", used: false },
	{ name: "JP", val: "jc penney", used: false },
	{ name: "JQ", val: "", used: false },
	{ name: "JS", val: "jose", used: false },
	{ name: "JT", val: "jot", used: false },
	{ name: "JU", val: "jew", used: false },
	{ name: "JV", val: "jv", used: false },
	{ name: "JW", val: "just wondering", used: false },
	{ name: "JX", val: "jax", used: false },
	// K
	{ name: "KB", val: "", used: false },
	{ name: "KC", val: "", used: false },
	{ name: "KD", val: "kid", used: false },
	{ name: "KF", val: "", used: false },
	{ name: "KG", val: "", used: false },
	{ name: "KH", val: "", used: false },
	{ name: "KI", val: "ki", used: false },
	{ name: "KJ", val: "kill joy", used: false },
	{ name: "KL", val: "kill", used: false },
	{ name: "KM", val: "kim", used: false },
	{ name: "KN", val: "ken", used: false },
	{ name: "KO", val: "knockout", used: false },
	{ name: "KP", val: "k plows", used: false },
	{ name: "KQ", val: "", used: false },
	{ name: "KS", val: "kill streak", used: false },
	{ name: "KT", val: "", used: false },
	{ name: "KU", val: "", used: false },
	{ name: "KV", val: "", used: false },
	{ name: "KW", val: "", used: false },
	{ name: "KX", val: "kix", used: false },
	// L
	{ name: "LB", val: "lab", used: false },
	{ name: "LC", val: "", used: false },
	{ name: "LD", val: "lad", used: false },
	{ name: "LF", val: "", used: false },
	{ name: "LG", val: "log", used: false },
	{ name: "LH", val: "", used: false },
	{ name: "LI", val: "long island", used: false },
	{ name: "LJ", val: "", used: false },
	{ name: "LK", val: "lick", used: false },
	{ name: "LM", val: "", used: false },
	{ name: "LN", val: "", used: false },
	{ name: "LO", val: "", used: false },
	{ name: "LP", val: "lip", used: false },
	{ name: "LQ", val: "", used: false },
	{ name: "LS", val: "", used: false },
	{ name: "LT", val: "", used: false },
	{ name: "LU", val: "lue", used: false },
	{ name: "LV", val: "", used: false },
	{ name: "LW", val: "low", used: false },
	{ name: "LX", val: "licks", used: false },
	// M
	{ name: "MB", val: "myrtle beach", used: false },
	{ name: "MC", val: "mic", used: false },
	{ name: "MD", val: "mad", used: false },
	{ name: "MF", val: "miss fortune", used: false },
	{ name: "MG", val: "mag", used: false },
	{ name: "MH", val: "", used: false },
	{ name: "MI", val: "my", used: false },
	{ name: "MJ", val: "michael jordan", used: false },
	{ name: "MK", val: "", used: false },
	{ name: "ML", val: "", used: false },
	{ name: "MN", val: "man", used: false },
	{ name: "MO", val: "", used: false },
	{ name: "MP", val: "map", used: false },
	{ name: "MQ", val: "", used: false },
	{ name: "MS", val: "miss", used: false },
	{ name: "MT", val: "", used: false },
	{ name: "MU", val: "", used: false },
	{ name: "MV", val: "move", used: false },
	{ name: "MW", val: "mow", used: false },
	{ name: "MX", val: "mix", used: false },
	// N
	{ name: "NB", val: "", used: false },
	{ name: "NC", val: "north carolina", used: false },
	{ name: "ND", val: "north dakota", used: false },
	{ name: "NF", val: "", used: false },
	{ name: "NG", val: "nog", used: false },
	{ name: "NH", val: "", used: false },
	{ name: "NI", val: "", used: false },
	{ name: "NJ", val: "new jersey", used: false },
	{ name: "NK", val: "", used: false },
	{ name: "NL", val: "nail", used: false },
	{ name: "NM", val: "nom", used: false },
	{ name: "NO", val: "no", used: false },
	{ name: "NP", val: "no problem", used: false },
	{ name: "NQ", val: "nesquik", used: false },
	{ name: "NS", val: "nos", used: false },
	{ name: "NT", val: "nut", used: false },
	{ name: "NU", val: "nunu", used: false },
	{ name: "NV", val: "nevada", used: false },
	{ name: "NW", val: "new", used: false },
	{ name: "NX", val: "nofx", used: false },
	// O
	{ name: "OB", val: "", used: false },
	{ name: "OC", val: "", used: false },
	{ name: "OD", val: "od", used: false },
	{ name: "OF", val: "of", used: false },
	{ name: "OG", val: "og", used: false },
	{ name: "OH", val: "ohio", used: false },
	{ name: "OI", val: "oi", used: false },
	{ name: "OJ", val: "orange juice", used: false },
	{ name: "OK", val: "ok", used: false },
	{ name: "OL", val: "ol", used: false },
	{ name: "OM", val: "", used: false },
	{ name: "ON", val: "on", used: false },
	{ name: "OP", val: "op", used: false },
	{ name: "OQ", val: "", used: false },
	{ name: "OS", val: "os", used: false },
	{ name: "OT", val: "", used: false },
	{ name: "OU", val: "", used: false },
	{ name: "OV", val: "", used: false },
	{ name: "OW", val: "ow", used: false },
	{ name: "OX", val: "ox", used: false },
	// P
	{ name: "PB", val: "pb", used: false },
	{ name: "PC", val: "pc", used: false },
	{ name: "PD", val: "", used: false },
	{ name: "PF", val: "puff", used: false },
	{ name: "PG", val: "pug", used: false },
	{ name: "PH", val: "", used: false },
	{ name: "PI", val: "pie", used: false },
	{ name: "PJ", val: "pj", used: false },
	{ name: "PK", val: "pk", used: false },
	{ name: "PL", val: "", used: false },
	{ name: "PM", val: "pompom", used: false },
	{ name: "PN", val: "", used: false },
	{ name: "PO", val: "po box", used: false },
	{ name: "PQ", val: "poke", used: false },
	{ name: "PS", val: "piss", used: false },
	{ name: "PT", val: "pot", used: false },
	{ name: "PU", val: "poo", used: false },
	{ name: "PV", val: "", used: false },
	{ name: "PW", val: "pow", used: false },
	{ name: "PX", val: "picks", used: false },
	// Q
	{ name: "QB", val: "quarterback", used: false },
	{ name: "QC", val: "", used: false },
	{ name: "QD", val: "squid", used: false },
	{ name: "QF", val: "queef", used: false },
	{ name: "QG", val: "", used: false },
	{ name: "QH", val: "", used: false },
	{ name: "QI", val: "", used: false },
	{ name: "QJ", val: "", used: false },
	{ name: "QK", val: "quick", used: false },
	{ name: "QL", val: "quail", used: false },
	{ name: "QM", val: "", used: false },
	{ name: "QN", val: "", used: false },
	{ name: "QO", val: "", used: false },
	{ name: "QP", val: "", used: false },
	{ name: "QS", val: "", used: false },
	{ name: "QT", val: "quit", used: false },
	{ name: "QU", val: "", used: false },
	{ name: "QV", val: "", used: false },
	{ name: "QW", val: "", used: false },
	{ name: "QX", val: "", used: false },
	// S
	{ name: "SB", val: "", used: false },
	{ name: "SC", val: "", used: false },
	{ name: "SD", val: "sad", used: false },
	{ name: "SF", val: "san fran", used: false },
	{ name: "SG", val: "", used: false },
	{ name: "SH", val: "sheena", used: false },
	{ name: "SI", val: "", used: false },
	{ name: "SJ", val: "", used: false },
	{ name: "SK", val: "suck", used: false },
	{ name: "SL", val: "", used: false },
	{ name: "SM", val: "", used: false },
	{ name: "SN", val: "", used: false },
	{ name: "SO", val: "", used: false },
	{ name: "SP", val: "", used: false },
	{ name: "SQ", val: "", used: false },
	{ name: "ST", val: "shit", used: false },
	{ name: "SU", val: "", used: false },
	{ name: "SV", val: "", used: false },
	{ name: "SW", val: "", used: false },
	{ name: "SX", val: "sucks", used: false },
	// T
	{ name: "TB", val: "tom brady", used: false },
	{ name: "TC", val: "", used: false },
	{ name: "TD", val: "", used: false },
	{ name: "TF", val: "", used: false },
	{ name: "TG", val: "", used: false },
	{ name: "TH", val: "", used: false },
	{ name: "TI", val: "", used: false },
	{ name: "TJ", val: "", used: false },
	{ name: "TK", val: "", used: false },
	{ name: "TL", val: "team liquid", used: false },
	{ name: "TM", val: "", used: false },
	{ name: "TN", val: "tennessee", used: false },
	{ name: "TO", val: "to", used: false },
	{ name: "TP", val: "toilet paper", used: false },
	{ name: "TQ", val: "", used: false },
	{ name: "TS", val: "", used: false },
	{ name: "TU", val: "tutu", used: false },
	{ name: "TV", val: "tv", used: false },
	{ name: "TW", val: "", used: false },
	{ name: "TX", val: "texas", used: false },
	// U
	{ name: "UB", val: "", used: false },
	{ name: "UC", val: "utica club", used: false },
	{ name: "UD", val: "udder", used: false },
	{ name: "UF", val: "", used: false },
	{ name: "UG", val: "ugg", used: false },
	{ name: "UH", val: "", used: false },
	{ name: "UI", val: "ui", used: false },
	{ name: "UJ", val: "", used: false },
	{ name: "UK", val: "uk", used: false },
	{ name: "UL", val: "", used: false },
	{ name: "UM", val: "", used: false },
	{ name: "UN", val: "", used: false },
	{ name: "UO", val: "", used: false },
	{ name: "UP", val: "up", used: false },
	{ name: "UQ", val: "", used: false },
	{ name: "US", val: "us", used: false },
	{ name: "UT", val: "utah", used: false },
	{ name: "UV", val: "uv", used: false },
	{ name: "UW", val: "", used: false },
	{ name: "UX", val: "", used: false },
	// V
	{ name: "VB", val: "virginia beach", used: false },
	{ name: "VC", val: "", used: false },
	{ name: "VD", val: "vd", used: false },
	{ name: "VF", val: "", used: false },
	{ name: "VG", val: "vlog", used: false },
	{ name: "VH", val: "", used: false },
	{ name: "VI", val: "", used: false },
	{ name: "VJ", val: "", used: false },
	{ name: "VK", val: "viking", used: false },
	{ name: "VL", val: "", used: false },
	{ name: "VM", val: "", used: false },
	{ name: "VN", val: "vernon", used: false },
	{ name: "VO", val: "voiceover", used: false },
	{ name: "VP", val: "vp", used: false },
	{ name: "VQ", val: "", used: false },
	{ name: "VS", val: "vs", used: false },
	{ name: "VT", val: "vermont", used: false },
	{ name: "VU", val: "", used: false },
	{ name: "VW", val: "view", used: false },
	{ name: "VX", val: "", used: false },
	// W
	{ name: "WB", val: "weeb", used: false },
	{ name: "WC", val: "", used: false },
	{ name: "WD", val: "weed", used: false },
	{ name: "WF", val: "wife", used: false },
	{ name: "WG", val: "wig", used: false },
	{ name: "WH", val: "", used: false },
	{ name: "WI", val: "", used: false },
	{ name: "WJ", val: "", used: false },
	{ name: "WK", val: "weak", used: false },
	{ name: "WL", val: "", used: false },
	{ name: "WM", val: "woman", used: false },
	{ name: "WN", val: "won", used: false },
	{ name: "WO", val: "", used: false },
	{ name: "WP", val: "whip", used: false },
	{ name: "WQ", val: "", used: false },
	{ name: "WS", val: "", used: false },
	{ name: "WT", val: "", used: false },
	{ name: "WU", val: "", used: false },
	{ name: "WV", val: "", used: false },
	{ name: "WX", val: "", used: false },
	// X
	{ name: "XB", val: "xtra big", used: false },
	{ name: "XC", val: "xtra chewy", used: false },
	{ name: "XD", val: "xtra dumb", used: false },
	{ name: "XF", val: "xtra fat", used: false },
	{ name: "XG", val: "xtra good", used: false },
	{ name: "XH", val: "xtra hot", used: false },
	{ name: "XI", val: "", used: false },
	{ name: "XJ", val: "", used: false },
	{ name: "XK", val: "", used: false },
	{ name: "XL", val: "xtra large", used: false },
	{ name: "XM", val: "xtra medium", used: false },
	{ name: "XN", val: "", used: false },
	{ name: "XO", val: "xo", used: false },
	{ name: "XP", val: "xtra petite", used: false },
	{ name: "XQ", val: "", used: false },
	{ name: "XS", val: "xtra small", used: false },
	{ name: "XT", val: "", used: false },
	{ name: "XU", val: "", used: false },
	{ name: "XV", val: "", used: false },
	{ name: "XW", val: "xtra wide", used: false }
];

$(document).ready(function(){
	getRandomPhrase();
	
	$("#answer").keypress(function(e){
		if(e.which == 13){
			checkAnswer($(this).val());
			getRandomPhrase();
			return false;  
		}
	}); 
	
	var numfilled = 0;
	$(phrases).each(function(index, elem){
		if(elem.val != "") numfilled++;
	});
	
	$("#stats").html(numfilled + " out of " + phrases.length + " have values");
});

function checkAnswer(txt){
	if(phrases[curr].val.toLowerCase() == $.trim(txt).toLowerCase()){
		correct++;
		$("body").animate({backgroundColor: "#4CAF50"}, function(){
			$("body").animate({backgroundColor: "#424242"});
		});
	}
	else{
		wrong++;
		$("body").animate({backgroundColor: "#F44336"}, function(){
			$("body").animate({backgroundColor: "#424242"});
		});
	}
	
	$("#score").html(correct + " for " + (correct + wrong))
}

function getRandomPhrase(){
	var num;
	if(countUnusedPhrases() == 0){
		$("#question").html(Math.floor((correct / (correct + wrong)) * 100) + "%");
		$("#answer").blur();
		$("#answer").val("");
		$("#answer").hide();
	}
	else{
		while(true){
			num = Math.floor(Math.random() * phrases.length);
			
			if(phrases[num].used == false){
				phrases[num].used = true;
				
				if(phrases[num].val != ""){ // skip blank ones
					break;
				}
			}
		}
		
		curr = num;
		$("#question").html(phrases[num].name);
		$("#answer").val("");
	}
}

function countUnusedPhrases(){
	var unused = 0;
	$(phrases).each(function(index, elem){
		if(elem.used == false) unused++;
	});
	return unused;
}